spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    routes:
      - id: restapi
        uri: lb://restapi
        predicates:
          - Path=/**

server:
  port: 8080

eureka:
  client:
    eureka-service-url-poll-interval-seconds: 15
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/